import Head from "next/head";
import { useEffect, useState } from "react";
import { createGlobalStyle } from "styled-components";
import { getAllPosts } from "../scripts/getAllPosts";
import styles from "../styles/Home.module.css";

type Metadata = {
  slug: string;
  title: string;
  date: string;
  excerpt: string;
};

type Posts = {
  metadata: Metadata;
  content: string;
};
const GlobalStyle = createGlobalStyle`

* {
  font-family: sans-serif;
  color: #333;
  box-sizing: border-box;
}

html,
body {
  margin: 0;
  padding: 0;
}
body {
  padding-left: 16px;
  padding-right: 16px;
  max-width: 700px;
  margin: auto;
}

h1,
h2,
h3,
h4,
h5
a {
  color: var(--primary);
}

button,
a {
  transition: opacity .3s;
  &:focus,
  &:hover {
    opacity: .5;
  }
}

.postsContainer {
  h1 {
    font-size: 2em;
    background-color: var(--primary);
    color: #fff;
    padding: 3px 5px;
    margin: 0;
    display: inline-block;
  }
}
.postsContainer__post {
  a {
    color: inherit;
    font-weight: bold;
    text-decoration: none;
  }
}
.headerContainer {
  display: flex;
  align-items: center;
  padding-top: 16px;
  padding-bottom: 16px;
  margin-bottom: 32px;
  img {
    max-width: 50px;
    border-radius: 100%;
    margin-right: 16px;
  }
  h1 {
    margin: 0;
  }
}
`;

const Home = ({ posts }: any) => {
  return (
    <div className={styles.container}>
      <GlobalStyle />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="headerContainer">
        {/*  <img src="https://github.com/omariosouto.png" /> */}
        <h1>Vitor Ferraz, Blogs</h1>
      </header>

      <section className="postsContainer">
        <h1>Posts</h1>
        {posts.map((post: Posts) => (
          <article key={post.metadata.title} className="postsContainer__post">
            <h2>
              <a href="#">{post.metadata.title}</a>
            </h2>
            <p>{post.metadata.excerpt}</p>
          </article>
        ))}
      </section>
    </div>
  );
};

export async function getStaticProps() {
  const posts = getAllPosts();

  return {
    props: { posts },
  };
}

export default Home;
